[package]
name = "rustc-tsan-testcase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.28.0", features = ["signal", "pthread"] }
once_cell = "1.19.0"
